### ISSUE TITLE
very consufing installation process

### ISSUE THREAD

**Issue by erikdemarco** [denoland/deno_install#291] opened 2024-08-16 03:18 UTC
Im using this command to install:

`curl -fsSL https://deno.land/install.sh | sh`

After 1 hour i realized i need to add some more setting to my $HOME/.basrc

Most users will expects smooth experience, this little decision wreck it. Why we cant just ask the user:

` If you dont want to call deno by its full path, you must add this line xxxx into your .basrc. Do you want us to add it automatically? Y/N?`

**Comment by kt3k** [comment] 2024-08-16 04:00
duplicate of #286

**Closed by kt3k** 2024-08-16 04:00 UTC
