### ISSUE TITLE
[ask] Which image to use for dockerization?

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [denoland/deno_install#162] opened 2020-09-21 16:32 UTC
Greetings, is there an official way to install deno with a docker image? or with a .yaml to use docker-compose.

**Comment by lucacasonato** [comment] 2020-09-21 16:38
No there is no official image right now. https://github.com/hayd/deno-docker are good though

Closing as duplicate of https://github.com/denoland/deno/issues/3356

**Closed by lucacasonato** 2020-09-21 16:38 UTC

**Comment by EdwinBetanc0urt** [comment] 2020-09-21 16:42
Thanks for responding @lucacasonato , I will check that docker image.
