### ISSUE TITLE
[FRE] Would there be official container images of deno on ducker hub ?

### ISSUE THREAD

**Issue by yw662** [denoland/deno_install#174] opened 2020-12-19 18:57 UTC
It would be great if one can use deno with docker by a simple `image: deno`, or `image: deno:debian` etc. It would be a great help for CI/CD, and so many other use cases.

Node.js have [these images](https://hub.docker.com/_/node) indeed.

**Comment by crowlKats** [comment] 2020-12-19 19:01
Duplicate of denoland/deno#3356

**Comment by lucacasonato** [comment] 2023-10-11 02:31
https://hub.docker.com/r/denoland/deno

**Closed by lucacasonato** 2023-10-11 02:31 UTC
