### ISSUE TITLE
Add Install Via Window Package Manager (winget)

### ISSUE THREAD

**Issue by ikushaldave** [denoland/deno_install#138] opened 2020-05-30 04:00 UTC
Microsoft Realise own package manager in BUILD 2020 so published Deno Manifest as Independent Software Vendors (ISVs)

Link - https://docs.microsoft.com/en-us/windows/package-manager/

So We Can  install Deno as Simple

`winget install Deno.land`

**Comment by MarkTiedemann** [comment] 2020-05-30 11:21
duplicate of https://github.com/denoland/deno/issues/5640

**Closed** 2020-05-30 13:57 UTC
