### ISSUE TITLE
install.sh puts an x86-64 binary on an aarch64 system

### ISSUE THREAD

**Issue by jrr** [denoland/deno_install#206] opened 2022-03-28 02:42 UTC
Just for fun I tried to install Deno on an arm64 Chromebook today. I hadn't specifically checked on platform support, but I figured the installer would tell me if there was a problem.

It turns out, nope, the installer doesn't tell you! It just grabs the x86-64 binary without checking what system it's on.

```
jrr@penguin:~$ curl -fsSL https://deno.land/install.sh | sh

######################################################################## 100.0%
Archive:  /home/jrr/.deno/bin/deno.zip
  inflating: /home/jrr/.deno/bin/deno  
Deno was installed successfully to /home/jrr/.deno/bin/deno
Run 'deno --help' to get started
jrr@penguin:~$ deno --help
-bash: /home/jrr/.deno/bin/deno: cannot execute binary file: Exec format error
jrr@penguin:~$ file .deno/bin/deno 
.deno/bin/deno: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[xxHash]=a66fbcf78776995f, with debug_info, not stripped
jrr@penguin:~$ uname -a
Linux penguin 5.10.92-14540-g0aec27ec0722 #1 SMP PREEMPT Thu Mar 17 18:57:37 PDT 2022 aarch64 GNU/Linux 
```

Hopefully [arm64 linux](https://github.com/denoland/deno/issues/1846) isn't too far off, but in the meantime perhaps install.sh should check the host architecture?

**Comment by crowlKats** [comment] 2022-03-28 08:14
Duplicate of https://github.com/denoland/deno_install/issues/199

**Closed by crowlKats** 2022-03-28 08:14 UTC
