### ISSUE TITLE
Support i686

### ISSUE THREAD

**Issue by vixalien** [denoland/deno_install#87] opened 2019-12-04 01:02 UTC
# Could you please support windows 32 bit machines for the build.

I'm using Windows NT 10 15063

Building the app is quite a sassle for me (as win32 users) because:
- My windows version does __not__ support symlinks even though I enabled developer options.
![Image attached](https://user-images.githubusercontent.com/37999241/70102942-5a7cc380-1642-11ea-8348-e32e15620b26.png)
- Installing MSVC is quite a sassle (I tried 5 times; the download can't finish)

By the way, I have very limited resources; RAM, CPU even Storage
Needed requirements
- [Updated Windows version](https://support.microsoft.com/en-us/help/4027667/windows-10-update) with Dev Options enabled (.symlinks not working for me)
- [Cargo](https://crates.io) or [Rust](https://www.rust-lang.org/) in general (not installable for me since it needs MSVC)
- [MSVC](https://visualstudio.microsoft.com/vs/community/) (not installable for me)
- [Python version 2](https://www.python.org/download/releases/2.7/), not 3 (working for me)

I think anyone with the listed above resources .
can build it ***NOW*** and send it because I think it is not a difficult task and 
I'm not even trying to go into node and I ***NEED*** it desperately. __PLEASE HELP__.

**Comment by MarkTiedemann** [comment] 2020-05-17 14:57
Duplicate of https://github.com/denoland/deno/issues/3438.

**Comment by MarkTiedemann** [comment] 2020-05-29 13:42
cc @bartlomieju Since https://github.com/denoland/deno/issues/3438 is closed now, I think this issue can be closed as well.

**Comment by vixalien** [comment] 2020-05-29 17:34
No, it was reopened (by me). Here's why:

> Whoa! the actual releases I thought are i686 are actually 64bit. Since this is still an issue, re-opening it.

**Comment by lucacasonato** [comment] 2020-09-21 16:40
Deno does not support Windows i686 and will not in the future. See https://github.com/denoland/deno/issues/3438#issuecomment-678697954

**Closed by lucacasonato** 2020-09-21 16:40 UTC
