### ISSUE TITLE
Deno upgrade fails on Windows 7

### ISSUE THREAD

**Issue by pedropaulosuzuki** [denoland/deno_install#181] opened 2021-03-06 17:00 UTC
I don't know if Windows 7 is still supported, but I cannot install Deno 1.8.0 on my Windows 7 machine, while it works fine on my Ubuntu 20.04 LTS, ElementaryOS 5.1 Hera and PopOS 20.10 operating systems. For me it is not a big deal, because I don't like using Windows that much, but as a teacher, many of my students still use Windows 7 or even Vista, so knowing if something is supposed to work on their machines is an important part of getting them into the Deno universe.

Obs: Deno 1.7.5 works fine, and I believe it has something to do with the WebGPU API in the new 1.8.0 version, which may be missing some DLL file or something.

![image](https://user-images.githubusercontent.com/32345702/110214578-fb7cae80-7e83-11eb-8224-cf4da778b3f0.png)

**Comment by kitsonk** [comment] 2021-03-06 21:34
Duplicate of denoland/deno#9608

**Closed by kitsonk** 2021-03-06 21:34 UTC

**Comment by pedropaulosuzuki** [comment] 2021-03-06 22:17
> Duplicate of [denoland/deno#9608](https://github.com/denoland/deno/issues/9608)

Actually it is not a duplicate of [denoland/deno#9608], because 1.7.5 works fine here, and 1.8.0 doesn't, while om 9608 he cannot go from 1.7.0 to 1.7.5, and both error codes are different.

**Comment by pedropaulosuzuki** [comment] 2021-03-06 23:01
The same problem, but running with RUST_BACKTRACE = 'full', in case it helps.
```powershell
$Env:RUST_BACKTRACE='full'
```

![image](https://user-images.githubusercontent.com/32345702/110224008-b887fe80-7eb6-11eb-8112-9d5b630a00cc.png)

**Comment by kitsonk** [comment] 2021-03-06 23:02
The fundamental problem is the we don't target and test on Windows 7.  That it works is coincidence versus intent.

**Comment by pedropaulosuzuki** [comment] 2021-03-07 00:51
> The fundamental problem is the we don't target and test on Windows 7. That it works is coincidence versus intent.

So any issue that happens on a Windows 7 machine will be marked as a duplicate of [denoland/deno#9608]?
