### ISSUE TITLE
Add `winget install deno`

### ISSUE THREAD

**Issue by Zerotask** [denoland/deno_install#208] opened 2022-04-23 09:25 UTC
I'll be great if one could install deno with the new builtin package manager for windows: [winget](https://github.com/microsoft/winget-cli)

```
winget install deno
```

The repository to add winget packages is https://github.com/microsoft/winget-pkgs

**Comment by crowlKats** [comment] 2022-04-23 09:28
Duplicate of https://github.com/denoland/deno/issues/5640

**Closed by crowlKats** 2022-04-23 09:28 UTC
