### ISSUE TITLE
Deno install script installs x86 binary when run on arm system

### ISSUE THREAD

**Issue by mattruzzi** [denoland/deno_install#222] opened 2022-07-26 22:45 UTC
```console
[matthew@fedora ~]$ uname -a
Linux fedora 5.18.13-200.fc36.aarch64 #1 SMP PREEMPT_DYNAMIC Fri Jul 22 13:44:25 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
[matthew@fedora ~]$ curl -fsSL https://deno.land/install.sh | sh
######################################################################## 100.0%
Archive:  /home/matthew/.deno/bin/deno.zip
  inflating: /home/matthew/.deno/bin/deno  
Deno was installed successfully to /home/matthew/.deno/bin/deno
Manually add the directory to your $HOME/.bashrc (or similar)
  export DENO_INSTALL="/home/matthew/.deno"
  export PATH="$DENO_INSTALL/bin:$PATH"
Run '/home/matthew/.deno/bin/deno --help' to get started    
[matthew@fedora ~]$   export DENO_INSTALL="/home/matthew/.deno"
  export PATH="$DENO_INSTALL/bin:$PATH"
[matthew@fedora ~]$ deno
bash: /home/matthew/.deno/bin/deno: cannot execute binary file: Exec format error
[matthew@fedora ~]$ file /home/matthew/.deno/bin/deno
/home/matthew/.deno/bin/deno: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[xxHash]=0aa9f7f5ebad2924, with debug_info, not stripped

```

**Comment by kitsonk** [comment] 2022-07-26 23:37
Duplicate of https://github.com/denoland/deno_install/issues/199

**Closed by kitsonk** 2022-07-26 23:37 UTC
Labels: duplicate
