### ISSUE TITLE
musl binaries

### ISSUE THREAD

**Issue by kasperk81** [denoland/deno_install#200] opened 2021-11-07 13:55 UTC
in alpine, ldd deno gives lots of warnings:

```
$ curl -fsSL https://deno.land/x/install/install.sh | sh
$ ldd ~/.deno/bin/deno

Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /home/kasper/.deno/bin/deno)
Error relocating /home/kasper/.deno/bin/deno: __memcpy_chk: symbol not found
Error relocating /home/kasper/.deno/bin/deno: __vfprintf_chk: symbol not found
Error relocating /home/kasper/.deno/bin/deno: __vsnprintf_chk: symbol not found
Error relocating /home/kasper/.deno/bin/deno: backtrace: symbol not found
Error relocating /home/kasper/.deno/bin/deno: backtrace_symbols: symbol not found
Error relocating /home/kasper/.deno/bin/deno: __mbrlen: symbol not found
Error relocating /home/kasper/.deno/bin/deno: strtoll_l: symbol not found
Error relocating /home/kasper/.deno/bin/deno: strtoull_l: symbol not found
Error relocating /home/kasper/.deno/bin/deno: __isinf: symbol not found
Error relocating /home/kasper/.deno/bin/deno: __memmove_chk: symbol not found
Error relocating /home/kasper/.deno/bin/deno: __register_atfork: symbol not found
Error relocating /home/kasper/.deno/bin/deno: __res_init: symbol not found
```
because install script downloads binary linked with glibc instead of musl libc, and this binary does not work if we try to run it.

**Comment by crowlKats** [comment] 2021-11-07 14:02
Duplicate of denoland/deno#3711

**Comment by kasperk81** [comment] 2021-11-07 14:24
that's a different repository altogether? https://deno.land/x/install/install.sh pointed me to this repo and there is no other issue to this effect..

**Comment by crowlKats** [comment] 2021-11-07 14:28
the `deno_install` repo is a set of scripts to download/install binaries. these binaries are created in the `deno` repo

**Comment by kitsonk** [comment] 2021-11-08 01:18
As stated, it is a duplicate.

**Closed by kitsonk** 2021-11-08 01:18 UTC
Labels: duplicate
